# Generated by Django 5.2.8 on 2026-05-26 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_base_url', models.URLField(blank=True)),
                ('ai_api_key', models.CharField(blank=True, max_length=512)),
                ('text_model', models.CharField(blank=True, max_length=128)),
                ('vision_model', models.CharField(blank=True, max_length=128)),
                ('obsidian_vault_path', models.CharField(blank=True, max_length=1024)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('arxiv_id', models.CharField(blank=True, max_length=64, unique=True)),
                ('doi', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(default='arXiv', max_length=64)),
                ('source_url', models.URLField(blank=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('local_pdf_path', models.CharField(blank=True, max_length=1024)),
                ('parsed_text', models.TextField(blank=True)),
                ('status', models.CharField(default='saved', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('arxiv_categories', models.JSONField(blank=True, default=list)),
                ('daily_limit', models.PositiveIntegerField(default=3)),
                ('obsidian_folder', models.CharField(blank=True, max_length=512)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('figure_index', models.PositiveIntegerField(default=1)),
                ('image_path', models.CharField(max_length=1024)),
                ('caption', models.TextField(blank=True)),
                ('context_text', models.TextField(blank=True)),
                ('figure_type', models.CharField(default='ordinary', max_length=64)),
                ('is_key_figure', models.BooleanField(default=False)),
                ('ai_description', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='core.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_direction', models.TextField(blank=True)),
                ('task_definition', models.TextField(blank=True)),
                ('input_data', models.TextField(blank=True)),
                ('output_result', models.TextField(blank=True)),
                ('network_overview', models.TextField(blank=True)),
                ('module_list', models.TextField(blank=True)),
                ('information_flow', models.TextField(blank=True)),
                ('loss_functions', models.TextField(blank=True)),
                ('training_process', models.TextField(blank=True)),
                ('inference_process', models.TextField(blank=True)),
                ('innovation_points', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('reproduction_questions', models.TextField(blank=True)),
                ('idea_hints', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('markdown_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='core.paper')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='core.researchtopic'),
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_date', models.DateField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('idea_hint', models.TextField(blank=True)),
                ('exported_to_obsidian', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.paper')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.researchtopic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('topic', 'paper', 'recommend_date'), name='unique_daily_recommendation')],
            },
        ),
    ]
