# Generated by Codex on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="published_date",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="paper",
            name="translated_abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="translated_title",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="version",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
