# Generated by Codex on 2026-06-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_paper_display_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True)),
                ("source", models.CharField(default="paperqa", max_length=64)),
                ("target_relative_path", models.CharField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paper", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="note", to="core.paper")),
            ],
        ),
    ]
